export const COLUMN_LABELS = {
  sequence_number: 'N° de séquence',
  extract_number: "N° d'extrait",
  account_number: 'N° de compte',
  execution_date: "Date d'exécution",
  accounting_date: 'Date de comptabilisation',
  value_date: 'Date valeur',
  amount: 'Montant',
  currency: 'Devise',
  transaction_type: 'Type de transaction',
  counterparty_account: 'Compte contrepartie',
  counterparty_name: 'Nom contrepartie',
  counterparty_street: 'Rue contrepartie',
  counterparty_city: 'Ville contrepartie',
  communication: 'Communication',
  details: 'Détails',
  status: 'Statut',
  rejection_reason: 'Motif du refus',
  bic: 'BIC',
  country_code: 'Code pays',
}
